// Generated by CoffeeScript 1.3.3
(function() {

  this.tuio.object_add(function(data) {
    return console.log('[object] add: sid=' + data.sid + ', fid=' + data.fid + ', x=' + data.x + ', y=' + data.y + ', angle=' + data.angle);
  });

  this.tuio.object_update(function(data) {
    return console.log('[object] update: sid=' + data.sid + ', fid=' + data.fid + ', x=' + data.x + ', y=' + data.y + ', angle=' + data.angle);
  });

  this.tuio.object_remove(function(data) {
    return console.log('[object] remove: sid=' + data.sid + ', fid=' + data.fid + ', x=' + data.x + ', y=' + data.y + ', angle=' + data.angle);
  });

  this.tuio.cursor_add(function(data) {
    return console.log('[cursor] add: sid=' + data.sid + ', fid=' + data.fid + ', x=' + data.x + ', y=' + data.y);
  });

  this.tuio.cursor_update(function(data) {
    return console.log('[cursor] update: sid=' + data.sid + ', fid=' + data.fid + ', x=' + data.x + ', y=' + data.y);
  });

  this.tuio.cursor_remove(function(data) {
    return console.log('[cursor] remove: sid=' + data.sid + ', fid=' + data.fid + ', x=' + data.x + ', y=' + data.y);
  });

  this.init = function() {
    console.log("starting");
    tuio.start();
    return console.log(tuio);
  };

}).call(this);
